### ISSUE TITLE
Doc: Add development commands in readme's "For Developer" section

### ISSUE THREAD

**Issue by sarthakpranesh** [sarthakpranesh/CpuRoller#1]
## Issue
The current documentation in readme.md under the `For Developer` section helps the developers compile the app directly into an executable file which does not allow the developer to see changes in real-time as they change the codebase

<br/>

## Changes required
Update the `For Developer` section and move points 4 & 5 to a sub-section called `Compile/Build/Package app` and in place of them add `wails serve`, `cd frontend`, `yarn install` and `yarn start` commands

<br/>

Make sure to fork the repo and work on the fork under a new branch. Once all your changes are complete, open a PR to the `master` branch of this repo

**Comment by pssingh21** [comment]
Hi! I would like to work on this.

**Comment by sarthakpranesh** [comment]
Hi @pssingh21, please feel free to open a pr resolving this issue and make sure to work on a fork. Happy hacking 🚀
