### ISSUE TITLE
Doc: Replace the screenshot sample.png with a GIF

### ISSUE THREAD

**Issue by sarthakpranesh** [sarthakpranesh/CpuRoller#3]
The documentation [readme](https://github.com/sarthakpranesh/CpuRoller/blob/master/README.md) currently contains a screenshot of the application. It would be nice to have a GIF in place of that to showcase the working of the app.

<br/>

Helpful steps
1. First build the app using the `Compile/Build/Package app` section in the documentation and run the app
2. Record a 10s video of the app running
3. Now convert this video into a GIF ( you can use https://ezgif.com/video-to-gif )
4. Delete the existing `sample.png` and add the new gif file
5. Update `readme.md` to display the new gif

<br/>

Make sure you fork this repo and work on the fork. Once all your changes are complete open a `PR` to the master branch of this repo. Happy hacking :rocket:

**Comment by SheldonnC** [comment]
May I work on this issue?

**Comment by sarthakpranesh** [comment]
Hey @SheldonnC, go ahead and make sure you work on the fork.

**Comment by SheldonnC** [comment]
Yeah.Sure:)
